[project]
name = "online-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "h5py>=3.13.0",
    "ipykernel>=6.29.5",
    "numpy>=2.2.4",
    "psifr>=0.9.3",
    "seaborn>=0.13.2",
]
